import os
import re
import markdown
import subprocess
from datetime import datetime
import shutil

YINWANG_BAK_DIR = "yinwang-bak"
ARCHIVES_DIR = "archives"

def get_file_created_date(filepath):
    """
    Tries to get the creation date of a file from git history.
    """
    try:
        # Get the date of the first commit that added this file
        # --diff-filter=A (Added) might miss if it was renamed, so just take the first commit involving the file?
        # Actually, for a blog post, the earliest commit date is a good proxy.
        cmd = ['git', 'log', '--diff-filter=A', '--follow', '--format=%aI', '--', filepath]
        result = subprocess.run(cmd, capture_output=True, text=True, cwd=YINWANG_BAK_DIR)
        output = result.stdout.strip().split('\n')
        if output and output[-1]: # Take the last one (earliest)
             return output[-1][:10] # YYYY-MM-DD
        
        # Fallback: just git log reverse
        cmd = ['git', 'log', '--reverse', '--format=%aI', '--', filepath]
        result = subprocess.run(cmd, capture_output=True, text=True, cwd=YINWANG_BAK_DIR)
        output = result.stdout.strip().split('\n')
        if output and output[0]:
            return output[0][:10]
            
    except Exception as e:
        print(f"Error getting git date for {filepath}: {e}")
    return None

def extract_date_from_content(content):
    """
    Extracts date from content like [2013.03] or headers.
    """
    # Pattern: [2013.03] or [2013.03.12]
    match = re.search(r'\[(\d{4})\.(\d{1,2})(?:\.(\d{1,2}))?\]', content)
    if match:
        year = match.group(1)
        month = match.group(2).zfill(2)
        day = match.group(3).zfill(2) if match.group(3) else "01"
        return f"{year}-{month}-{day}"
    return None

def sanitize_filename(name):
    """Sanitizes the title to be filename friendly."""
    # This is for the output filename
    # replace spaces with underscores, remove special chars
    # However, existing archive uses Chinese filenames, so maybe we just keep it simple?
    # Generate_site.py seems to handle unicode.
    # Let's just make sure it doesn't contain slashes or colons.
    name = name.replace('/', '_').replace(':', '：')
    return name


def get_existing_title_map():
    """
    Scans ARCHIVES_DIR for existing articles to build a map:
    { "Title": "blog-cn_xxxx" }
    """
    if not os.path.exists(ARCHIVES_DIR):
        return {}
    
    title_map = {}
    for f in os.listdir(ARCHIVES_DIR):
        if not f.endswith(".html"):
            continue
            
        # Parse title from file content
        filepath = os.path.join(ARCHIVES_DIR, f)
        try:
            with open(filepath, 'r', encoding='utf-8', errors='ignore') as file:
                content = file.read()
                
            # Extract title using simple regex or the extract_title function logic
            # Simpler here: regex for <title> or <h1>
            match = re.search(r'<title[^>]*>(.*?)</title>', content, re.IGNORECASE | re.DOTALL)
            if match:
                title = match.group(1).strip()
                # Store mapping if it's a blog-cn file
                # If there are multiple versions, any of them works to give us the base name prefix.
                # structure: base_name_YYYYMMDD.html
                # We want base_name.
                if '_20' in f: # Heuristic for date suffix
                    base_name = f.rsplit('_', 1)[0]
                else:
                    base_name = os.path.splitext(f)[0]
                    
                if title and base_name.startswith('blog-cn'):
                     title_map[title] = base_name
        except Exception:
            continue
            
    return title_map

def convert_and_import():
    if not os.path.exists(ARCHIVES_DIR):
        os.makedirs(ARCHIVES_DIR)

    # Clean up previous run's artifacts (files that don't start with blog-cn, tweet, homepage, index, resources, posts, tags, about)
    # Be careful not to delete legitimate files.
    # The previous run generated files like "Title_YYYYMMDD.html".
    # Existing files are mostly "blog-cn...".
    # So we can look for files that are NOT in the allowed list and were likely generated by us.
    # But for safety, let's just overwrite correct ones and let user manually delete junk if needed?
    # Or strict cleanup: delete files that we know we created? 
    # Let's clean up files that don't match the new naming convention if they originated from this script.
    # Actually, the user asked to "Clean up previous import artifacts".
    # Previous run produced files like "扶门的礼仪_20180328.html".
    # We want "blog-cn_...".
    # So we can delete files that DO NOT start with "blog-cn", "resources", "homepage", "index", "tweet", "about", "posts", "tags"
    # AND are in our list of imported titles?
    # This is risky on user data. Let's rely on overwriting/creating new ones, and maybe a separate cleanup step or just print what to delete.
    
    title_map = get_existing_title_map()
    print(f"Loaded {len(title_map)} existing article titles.")

    files = [f for f in os.listdir(YINWANG_BAK_DIR) if f.endswith('.md')]
    print(f"Found {len(files)} markdown files in {YINWANG_BAK_DIR}")

    count = 0
    new_count = 0
    merged_count = 0


    for filename in files:
        filepath = os.path.join(YINWANG_BAK_DIR, filename)
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()

        # Initialize Markdown with meta extension
        md = markdown.Markdown(extensions=['meta'])

        html_body = md.convert(content)
        
        # Remove duplicate title (first h1) from content if it exists
        # Some markdown files start with '# Title', which becomes <h1>Title</h1>.
        # Since we manually add <h1>{title}</h1>, we should remove the redundant one.
        match = re.search(r'^\s*<h1>(.*?)</h1>', html_body, re.IGNORECASE | re.DOTALL)
        if match:
            # We can optionally check if match.group(1) is similar to title, 
            # but usually the first H1 is indeed the title in these files.
            # Let's remove it to avoid duplication.
            html_body = html_body[match.end():].strip()
        
        # Extract metadata
        meta = getattr(md, 'Meta', {})
        
        # 1. Title
        if 'title' in meta and meta['title']:
            # Meta values are lists
            title = meta['title'][0]
        else:
             title = os.path.splitext(filename)[0]

        # 2. Date
        date_str = None
        if 'date' in meta and meta['date']:
            # date format in file: 2015-07-04 00:00:00 -0700
            raw_date = meta['date'][0]
            # Try to grab just YYYY-MM-DD
            match = re.search(r'(\d{4}-\d{2}-\d{2})', raw_date)
            if match:
                date_str = match.group(1)
        
        if not date_str:
            date_str = extract_date_from_content(content)
        if not date_str:
            date_str = get_file_created_date(filename)
        
        if not date_str:
            print(f"Warning: No date found for {filename}, using 2000-01-01")
            date_str = "2000-01-01"

        full_html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{title}</title>
</head>
<body>
<h1>{title}</h1>
<div class="date">{date_str}</div>
{html_body}
</body>
</html>"""

        clean_date = date_str.replace('-', '')
        
        # Decide base name
        if title in title_map:
            base_name = title_map[title]
            merged_count += 1
        else:
            # Create new base name
            sanitized_title = sanitize_filename(title)
            # Ensure it is ASCII friendly for URL? Existing ones use pinyin/english?
            # Existing: blog-cn_2013_03_01_linux
            # or blog-cn_2012_07_04_printing
            # But the user asked for simple local runnable.
            # Using chinese in filename is usually fine on modern OS.
            # Let's prefix with blog-cn_ to force it into homepage.
            base_name = f"blog-cn_{clean_date}_{sanitized_title}"
            new_count += 1
            
        output_filename = f"{base_name}_{clean_date}.html"
        output_path = os.path.join(ARCHIVES_DIR, output_filename)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(full_html)
        
        count += 1
        print(f"Imported: {output_filename}")

    print(f"Successfully processed {count} articles.")
    print(f"Merged: {merged_count}, New: {new_count}")


if __name__ == "__main__":
    convert_and_import()
